config/routes.rb
Rails.application.routes.draw do

  resources :platforms
  get 'teams/index'
  get 'teams/new'
  get 'teams/show'
  get 'teams/edit'
  #API ROUTES
  namespace :api do
    namespace :v1 do
      #ADMIN API ROUTES
      namespace :admin do
        resources :games, only: [:index, :create, :show, :update, :destroy] do
          collection do
            get :game_types
            get :get_all_games
          end
        end
        resources :tournaments, only: [:index, :create, :show, :update, :destroy]
      end

      post '/user/sign_in' => 'authentication#sign_in'
      post  '/user/sign_up' => "registrations#sign_up"
      post  '/user/sign_up_with_google' => "registrations#sign_up_with_google"
      resources :teams
      resources :players
      resources :tournament_registrations
      get '/lastest_tournaments' => "tournament_registrations#latest_tournaments"
    end
  end

  #WEB ROUTES
  resources :game_types
  resources :games
  resources :teams
  resources :tournaments do
    resources :tournament_registrations
  end
  devise_for :super_admins
  devise_scope :super_admin do
    authenticated :super_admin do
      root 'tournaments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
	belongs_to :tournamentable, polymorphic: true
	belongs_to :game
	has_many :participant_teams, dependent: :destroy
	has_many :matches, dependent: :destroy
	has_many :groups, dependent: :destroy

	mount_uploader :banner, BannerUploader

	#SCOPES
	scope :pending, -> { where(status: 'pending')}

	#VALIDATIONS
	validates :name, :start_date, :end_date, presence: true
	validates :end_date, comparison: { comparison_attr: :start_date, message: "must be greater than start date" }
  	validates :start_date, comparison: { comparison_attr: :end_date, operator: :<, message: "must be less than end date" }


	NO_OF_WINNERS = {
		1 => 1,
		2 => 2,
		3 => 3
	}

	MAX_TEAM = {
		'25' => 25,
		'50' => 50,
		'100' => 100
	}

	STATUS = {
		'Pending' => 'pending',
		'Running' => 'running',
		'Completed' => 'completed',
		'Cancled' => 'cancled'
	}

	private

	def check_start_end_date
	    unless end_date > start_date
	    	debugger
	      errors.add(:end_date, "end date should be greater than start date")
	    end
 	end
end

app/controllers/api/v1/admin/tournaments_controller.rb
module Api
	module V1
		module Admin
			class TournamentsController < Api::V1::ApiController
				before_action :authorize_request
				#before_action :is_admin
				before_action :set_tournament, only: [:show, :update, :destroy]

				def index
					begin
						@tournaments = Tournament.all
						tournaments_serializer = @tournaments.map{|tournament| TournamentSerializer.new(tournament).serializable_hash}
						render json: {success: true, tournaments: tournaments_serializer}
					rescue Exception => e
						render json: {error: e.message}, status: :unprocessable_entity
					end
				end

				def create
					begin
						@tournament = Tournament.new(tournament_params)
						@tournament.tournamentable = @current_user
						if @tournament.save
							render json: {success: true, tournament: @tournament, message: 'Tournament created successfully!'}
						else
							render json: {sucess: false, error: @tournament.errors.full_messages&.first}, status: :unprocessable_entity
						end
					rescue Exception => e
						render json: {error: e.message}, status: :unprocessable_entity
					end
				end

				def show
					render json: {tournament: @tournament}
				end

				def update
					begin
						if @tournament.update(tournament_params)
							render json: {success: true, tournament: @tournament, message: 'Tournament updated successfully!'}
						else
							render json: {error: @tournament.errors.full_message}
						end
					rescue Exception => e
						render json: {error: e.message}, status: :unprocessable_entity
					end
				end

				def destroy
					begin
						if @tournament.destroy
							render json: {success: true, message: 'Tournament Deleted successfully!'}
						else
							render json: {error: @tournament.errors.full_message}
						end
					rescue Exception => e
						render json: {error: e.message}, status: :unprocessable_entity
					end
				end

				private

				def tournament_params
					params.require(:tournament).permit(:name, :game_id, :start_date, :end_date, :entry_fee, :winner_1_prize, :winner_2_prize, :winner_3_prize, :max_team, :no_of_winners, :status, :platform, :banner)
				end

				def set_tournament
					@tournament = Tournament.find(params[:id])
					render json: {error: 'Tournament not found'}, status: :unprocessable_entity if @tournament.nil?
				end
			end
		end
	end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:edit, :show, :update, :destroy]
  def index
    @tournaments = Tournament.includes(:tournamentable, :game, :participant_teams).all
  end

  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def show
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.tournamentable = current_super_admin
    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournament_path(@tournament), notice: "Tournament was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_path(@tournament), notice: "Tournament was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    respond_to do |format|
      if @tournament.destroy
        format.html { redirect_to tournaments_path, notice: "Tournament was successfully Deleted." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end



  private

  def set_tournament
    @tournament = Tournament.includes(:participant_teams).find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :start_date, :end_date, :game_id, :status, :no_of_winners, :entry_fee, :max_team, :winner_1_prize, :winner_2_prize, :winner_3_prize)
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper

	def all_games(user_id)
		Game.where(gameable_id: user_id).map{|game| [game.name, game.id]}
	end
end

app/views/tournaments/_form.html.erb
<hr class="featurette-divider m-3 text-dark">
<div class="container my-3">
      <%= form_for(@tournament) do |f| %>
        <div class="row mt-3">
            <div class="col-md-4">
              <%= label_tag 'name' %><span class="required" style="color: red;">*</span>
              <%= f.text_field :name, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :name) %></p>
            </div>
            <div class="col-md-4">
              <%= label_tag 'start_date' %><span class="required" style="color: red;">*</span>
              <%= f.date_field :start_date, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :start_date) %></p>
            </div>
            <div class="col-md-4">
              <%= label_tag 'end_date' %><span class="required" style="color: red;">*</span>
              <%= f.date_field :end_date, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :end_date) %></p>
            </div>
        </div>

        <div class="row mt-3">
          <div class="col-md-4">
            <%= label_tag 'Game' %><span class="required" style="color: red;">*</span>
            <%= f.select :game_id, options_for_select(all_games(current_super_admin.id), @tournament.game_id),{}, {required: true, class: "form-control"} %>
            <p class='error'><%= show_errors(@tournament, :Game) %></p>
          </div>
          <div class="col-md-4">
              <%= label_tag 'entry_fee' %><span class="required" style="color: red;">*</span>
              <%= f.number_field :entry_fee, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :entry_fee) %></p>
          </div>
          <div class="col-md-4">
              <%= label_tag 'no_of_winners' %><span class="required" style="color: red;">*</span>
              <%= f.select :no_of_winners, options_for_select(Tournament::NO_OF_WINNERS, @tournament.no_of_winners), {},{ required: false, class: "form-select"} %>
              <p class='error'><%= show_errors(@tournament, :no_of_winners) %></p>
            </div>
        </div>
        <div class="row mt-3">
         <div class="col-md-4">
              <%= label_tag 'max_team' %><span class="required" style="color: red;">*</span>
              <%= f.select :max_team, options_for_select(Tournament::MAX_TEAM),{},{ required: false, class: "form-select"} %>
              <p class='error'><%= show_errors(@tournament, :max_team) %></p>
          </div>
          <div class="col-md-4">
              <%= label_tag 'status' %><span class="required" style="color: red;">*</span>
              <%= f.select :status, options_for_select(Tournament::STATUS), {}, {required: false, class: "form-select"} %>
              <p class='error'><%= show_errors(@tournament, :status) %></p>
            </div>
            <div class="col-md-4">
              <%= label_tag 'winner_1_prize' %><span class="required" style="color: red;">*</span>
              <%= f.number_field :winner_1_prize, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :winner_1_prize) %></p>
            </div>
      </div>
        <div class="row mt-3">
            <div class="col-md-4">
              <%= label_tag 'winner_2_prize' %><span class="required" style="color: red;">*</span>
              <%= f.number_field :winner_2_prize, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :winner_2_prize) %></p>
            </div>
            <div class="col-md-4">
              <%= label_tag 'winner_3_prize' %><span class="required" style="color: red;">*</span>
              <%= f.number_field :winner_3_prize, required: false, class: "form-control" %>
              <p class='error'><%= show_errors(@tournament, :winner_3_prize) %></p>
            </div>
        </div>

      <div class="action mt-4" align="center">
        <%= f.submit 'Submit', class: "btn btn-success"%>
      </div>
    </div>
  <% end %>
  </div>

app/views/tournaments/_tournament_table.html.erb
<table id="tournaments-table" class="dispaly table table-striped-5 border ">
  <thead style="background-color: rgb(0, 65, 114);" >
    <tr>
      <th scope="col" class="text-white fs-5">Name</th>-
      <th scope="col" class="text-white fs-5">Game</th>
      <th scope="col" class="text-white fs-5">Owner</th>
      <th scope="col" class="text-white fs-5">Participated Team</th>
      <th scope="col" class="text-white fs-5">Status</th>
      <th scope="col" class="text-center text-white fs-5">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr class="text-start">
        <td><%= tournament.name %></td>
        <td><%= tournament.game&.name %></td>
        <td><%= tournament.tournamentable.name %></td>
        <td><%= tournament.participant_teams.count %></td>
        <td><%= tournament.status&.capitalize %></td>
        <td class="text-center">
          <%= link_to 'Show', tournament, class:"btn btn-sm text-dark ", style:"background-color: #E2DE09;" %> |
          <%= link_to 'Edit', edit_tournament_path(tournament),class:"btn btn-sm text-white ", style:"background-color: green;" %> |
          <%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-sm text-white ", style:"background-color: #B51C07;" %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/tournaments/edit.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row text-center pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"mx-5 text-dark fs-2 align-items-start "%> 
    </div>
    <div class="col-8">
      <h2 class="text-center">Updating Tournament</h2>    
    </div>
		<%= render 'form' %>
  </div>
</div>

app/views/tournaments/index.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row p-3 pe-lg-0 py-lg-3 ">
    <div class="d-flex justify-content-md-between">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"text-dark fs-2"%> 
      <h2 style="color: rgb(0, 65, 114);"><span><i class="fa fa-trophy"></i></span>Tournaments</h2> 
      <%= link_to ('<i class="fa fa-plus-circle "></i> Add Tournament').html_safe,new_tournament_path, class:"btn text-white fs-5 ", style:"background-color: rgb(0, 65, 114);"%>  
    </div>
  </div>
</div>

<div class="container-fluid my-5">
  <div class="row d-flex justify-content-center text-center p-1 pb-0 pe-lg-0 pt-lg-1 align-items-center"> 
    <div class="col-12 my-4 rounded-4 border shadow-lg">
      <p id="notice"><%= notice %></p>
      <%= render "tournaments/tournament_table"%>
    </div>
  </div>
</div>

app/views/tournaments/new.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row text-center pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"mx-5 text-dark fs-2 align-items-start "%> 
    </div>
    <div class="col-8">
      <h2 class="text-center">Adding New Tournament</h2>    
    </div>
		<%= render 'form' %>
  </div>
</div> 

app/views/tournaments/show.html.erb
<div class="container-fluid mt-5 border rounded-4 shadow-lg">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
  	<div class="col-2">
  		<%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"mx-5 text-dark fs-2 align-items-start "%>
  	</div>
  	<div class="col-7">
			<h2 class="text-center">  </h2>
  	</div>
  	  	<div class="col-3">
			<%= link_to 'Add Team For Tournament', new_tournament_tournament_registration_path(@tournament),class:"btn text-white fs-5", style:"background-color: rgb(0, 65, 114);" %>
  	</div>
  </div>
</div>

<div class="container-fluid border shadow-lg mt-5 " style="width: 100%;">
	<div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
		<div class="col">
      <h4>Tournament Details</h4>
			<div class="container-fluid border shadow-sm my-3">
				<div class="row mt-3 text-start">
					<div class="col-md-4">
						<p><strong>Name:</strong> <%= @tournament.name %></p>
					</div>
					<div class="col-md-4 ">
						<p><strong>Date: </strong> <%= @tournament.start_date&.strftime("%d/%b/%Y") %> - <%= @tournament.end_date&.strftime("%d/%b/%Y") %> </p>
					</div>
          <div class="col-md-4">
						<p><strong>Created By :</strong> <%= @tournament.tournamentable&.name %> </p>
					</div>
				</div>
				<div class="row mt-3 text-start">
					<div class="col-md-4">
						<p> <strong>Game:</strong> <%= (@tournament.game.name) %></p>
						<p class="fw-bold fs-3"></p>
					</div>
					<div class="col-md-4">
						<p><strong> Entry Fee:</strong> <%= @tournament.entry_fee %></p>
					</div>
          <div class="col-md-4">
						<p><strong>Number of Winners:</strong> <%= @tournament.no_of_winners %></p>
					</div>
				</div>
				<div class="row mt-3 text-start">
	        <div class="col-md-4">
						<p><strong>Winner 1 Prize:</strong> <%= @tournament.winner_1_prize %></p>
					</div>
          <div class="col-md-4">
						<p><strong>Winner 2 Prize:</strong> <%= @tournament.winner_2_prize %></p>
					</div>
          <div class="col-md-4">
						<p><strong>Winner 3 Prize:</strong> <%= @tournament.winner_3_prize %></p>
					</div>
				</div>
				<div class="row mt-3 text-start">
					<div class="col-md-4">
						<p><strong>Max Team Participate:</strong> <%= @tournament.max_team %></p>
					</div>
					<div class="col-md-4">
						<p><strong>Status:</strong> <%= @tournament.status %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="participated_teams">
  <div class="container-fluid border shadow-lg mt-5 " style="width: 100%;">
  	<div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
      <div class="col">
        <h4>Teams</h4>
  			<div class="container-fluid border shadow-sm my-3">
          <table class="table">
            <thead>
              <th>Team Name</th>
              <th>Players</th>
              <th>Payment</th>
              <th>Participated Date</th>
            </thead>
            <tbody>
              <% @tournament.participant_teams.each do |participant_team| %>
                <tr>
                  <td><%= participant_team.team.team_name %></td>
                  <td><%= participant_team.team.players.count %></td>
                  <td>Done</td>
                  <td><%= participant_team.created_at.strftime("%d-%m-%Y") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>