config/routes.rb
Rails.application.routes.draw do

  resources :platforms
  get 'teams/index'
  get 'teams/new'
  get 'teams/show'
  get 'teams/edit'
  #API ROUTES
  namespace :api do
    namespace :v1 do
      #ADMIN API ROUTES
      namespace :admin do
        resources :games, only: [:index, :create, :show, :update, :destroy] do
          collection do
            get :game_types
            get :get_all_games
          end
        end
        resources :tournaments, only: [:index, :create, :show, :update, :destroy]
      end

      post '/user/sign_in' => 'authentication#sign_in'
      post  '/user/sign_up' => "registrations#sign_up"
      post  '/user/sign_up_with_google' => "registrations#sign_up_with_google"
      resources :teams
      resources :players
      resources :tournament_registrations
      get '/lastest_tournaments' => "tournament_registrations#latest_tournaments"
    end
  end

  #WEB ROUTES
  resources :game_types
  resources :games
  resources :teams
  resources :tournaments do
    resources :tournament_registrations
  end
  devise_for :super_admins
  devise_scope :super_admin do
    authenticated :super_admin do
      root 'tournaments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
	mount_uploader :game_logo, GameLogoUploader
	belongs_to :gameable, polymorphic: true
	belongs_to :game_type
	has_many :tournaments, dependent: :destroy
	validates :name, presence: true
	#validates :name, uniqueness: true

	# def logo_will_change!
 #    super
 #    self.logo.cache! if logo.present?
 #  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
	validates :game_type, presence: true
	validates :game_type, uniqueness: true
end

app/controllers/api/v1/admin/games_controller.rb
module Api
	module V1
		module Admin
			class GamesController < Api::V1::ApiController
				before_action :authorize_request
				#before_action :is_admin
				before_action :set_game, only: [:show, :update, :destroy]

				def index
					begin
						@games = @current_user.games.includes(:game_type)
						game_serializer = @games.map{|game| Api::V1::Admin::GameSerializer.new(game).serializable_hash}
						render json: {success: true, games: game_serializer}
					rescue Exception => e
						render json: { error: e.message }, status: :unprocessable_entity
					end
				end

				def get_all_games
					begin
						
						# Fetch games created by current user or super admins
						games = Game.joins("LEFT OUTER JOIN users ON gameable_type = 'User' AND gameable_id = users.id")
						            .joins("LEFT OUTER JOIN super_admins ON gameable_type = 'SuperAdmin' AND gameable_id = super_admins.id")
						            .where("(gameable_type = 'User' AND gameable_id = ?) OR super_admins.id IS NOT NULL", @current_user.id)
						            .select("games.*")
						# Group games by gameable_type
						games_by_type = games.group_by(&:gameable_type)

						# Build the result hash
						games_hash = {
						  super_admin_games: games_by_type['SuperAdmin']&.map{|game| {id: game.id, name: game.name}} || [],
						  your_games: games_by_type['User']&.map{|game| {id: game.id, name: game.name}} || []
						}

						render json: {success: true, games_data: games_hash}
					rescue Exception => e
						render json: {success: false, errors: e.message}, status: :unprocessable_entity
					end
				end

				def create
					begin
						@game = Game.new(game_params)
						@game.gameable = @current_user
						#@game.game_logo = game_params["game_logo"] if game_params["game_logo"].present?
						if @game.save
							render json: {success: true, data: {game: @game}, message: 'Game Created Successfully!'}
						else
							render json: { error: @game.errors.full_messages }, status: :unprocessable_entity
						end
					rescue Exception => e
						render json: { error: e.message }, status: :unprocessable_entity
					end
				end


				def show
					begin
						if @game.present?
							render json: {success: true, game: @game}
						else
							render json: {error: 'Game not Found'}, status: :unprocessable_entity
						end
					rescue Exception => e
						render json: {error: e.message}, status: :unprocessable_entity
					end
				end


				def update
					begin
						if @game.update(game_params)
							render json: {success: true, message: 'Game Updated Successfully!'}
						else
							render json: { error: @game.errors.full_messages }, status: :unprocessable_entity
						end
					rescue Exception => e
						render json: { error: e.message }, status: :unprocessable_entity
					end
				end

				def destory
					begin
						if @game.destory
							render json: {success: true, message: 'Game Deleted Successfully!'}
						else
							render json: { error: @game.errors.full_messages }, status: :unprocessable_entity
						end
					rescue Exception => e
						render json: { error: e.message }, status: :unprocessable_entity
					end
				end

				def game_types
					begin
						@game_types = GameType.all.map{|game_type| Api::V1::Admin::GameTypesSerializer.new(game_type).serializable_hash}
						render json: {success: true, game_types: @game_types}
					rescue Exception => e
						render json: { error: e.message }, status: :unprocessable_entity
					end
				end

				private

				def set_game
					@game = Game.find(params[:id])
					render json: {error: 'Game Not Found'} if @game.nil?
				end

				def game_params
					params.require(:game).permit(:id, :name, :game_type_id, :game_logo)
				end
			end
		end
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.includes(:gameable, :game_type).all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.gameable = current_super_admin
    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    respond_to do |format|
      if @game.destroy
        format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      else  
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :game_type_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<hr class="featurette-divider m-3 text-dark">
<div class="container my-3">
      <%= form_with(model: game) do |form| %>
        <div class="row mt-3">
            <div class="col-md-4 fs-4">
              <%= label_tag 'name' %><span class="required" style="color: red;">*</span>
              <%= form.text_field :name, class: "form-control" %>
              <p class='error'><%= show_errors(game, :name) %></p>
            </div>
            <div class="col-md-4 fs-4">
              <%= label_tag 'game_type' %><span class="required" style="color: red;">*</span>
              <%= form.select :game_type_id, options_for_select(GameType.all.map{|game_type| [game_type.game_type, game_type.id]}),{}, class: "form-select" %>
              <p class='error'><%= show_errors(game, :game_type_id) %></p>
            </div>
        </div>                
      <div class="action mt-4 " align="center">
        <%= form.submit 'Submit', class: "btn btn-success fs-5"%>
      </div>
    </div>
  <% end %>
  </div>

app/views/games/_game_table.html.erb
<table id="games-table" class="dispaly table table-striped-5 border">
  <thead style="background-color: rgb(0, 65, 114);" >
    <tr>
      <th scope="col" class="text-white fs-5">Name</th>
      <th scope="col" class="text-white fs-5">Game Type</th>
      <th scope="col" class="text-white fs-5">Created By</th>
      <th scope="col" class="text-center text-white fs-5">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr class="text-start">
        <td><%= game.name %></td>
        <td><%= game.game_type&.game_type %></td>
        <td><%= game.gameable.email %></td>
        <td class="text-center">
          <%= link_to 'Show', game, class:"btn btn-sm text-dark ", style:"background-color: #E2DE09;" %> | 
          <%= link_to 'Edit', edit_game_path(game),class:"btn btn-sm text-white ", style:"background-color: green;" %> | 
          <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-sm text-white ", style:"background-color: #B51C07;" %>
        </td>
      </tr>
    <%end%>    
  </tbody>
</table>

app/views/games/edit.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row text-center pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, games_path, class:"mx-5 text-dark fs-2 align-items-start "%> 
    </div>
    <div class="col-8">
      <h2 class="text-center">Updating Game</h2>    
    </div>
		<%= render 'form', game: @game %>
  </div>
</div>

app/views/games/index.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row text-center pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"mx-5 text-dark fs-2 align-items-start "%>
    </div>
    <div class="col-8">
      <h2 class="text-center"><span><i class="fa fa-gamepad"></i></span> Games</h2>    
    </div>
    <div class="col-2">
      <%= link_to ('<i class="fa fa-plus-circle "></i> Add Game').html_safe,new_game_path, class:"btn text-white fs-5", style:"background-color: rgb(0, 65, 114);" %>
    </div>
  </div>
</div> 

<div class="container-fluid my-5">
  <div class="row d-flex justify-content-center text-center p-1 pb-0 pe-lg-0 pt-lg-1 align-items-center"> 
    <div class="col-12 my-4 rounded-4 border shadow-lg">
      <p id="notice"><%= notice %></p>
      <%= render "games/game_table"%>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="container-fluid my-5 border rounded-4 shadow-lg">
  <div class="row text-center pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, games_path, class:"mx-5 text-dark fs-2 align-items-start "%> 
    </div>
    <div class="col-8">
      <h2 class="text-center">Adding Game</h2>    
    </div>
	<%= render 'form', game: @game %>
  </div>
</div>

app/views/games/show.html.erb
<div class="container-fluid mt-5 border shadow-lg">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
    <div class="col-2">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, tournaments_path, class:"mx-5 text-dark fs-2 align-items-start "%>  
    </div>
    <div class="col-8">
      <h2 class="text-center"><%= @game.name%> / Tournament</h2>    
    </div>
        <div class="col-2">
      <%= link_to "Edit", edit_game_path(@game), class:"btn btn-outline text-white btn-lg ", style:"background-color: rgb(0, 65, 114);"%>   
    </div>
  </div>
</div>

<div class="container-fluid border shadow-lg mt-5 " style="width: 100%;">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
    <div class="col">
      <div class="container border shadow-sm my-5">
        <div class="row mt-3 text-start"> 
          <div class="col-md-4">
            <p> (Name) :</p>
            <p class="fw-bold fs-3"><%= @game.name %></p>
          </div>  
          <div class="col-md-4">
            <p> (Game Type) :</p>
            <p class="fw-bold fs-3"><%= @game.game_type&.game_type %>)</p>
          </div>
      </div>
    </div>  
  </div>
</div>    