config/routes.rb
Rails.application.routes.draw do

  resources :platforms
  get 'teams/index'
  get 'teams/new'
  get 'teams/show'
  get 'teams/edit'
  #API ROUTES
  namespace :api do
    namespace :v1 do
      #ADMIN API ROUTES
      namespace :admin do
        resources :games, only: [:index, :create, :show, :update, :destroy] do
          collection do
            get :game_types
            get :get_all_games
          end
        end
        resources :tournaments, only: [:index, :create, :show, :update, :destroy]
      end

      post '/user/sign_in' => 'authentication#sign_in'
      post  '/user/sign_up' => "registrations#sign_up"
      post  '/user/sign_up_with_google' => "registrations#sign_up_with_google"
      resources :teams
      resources :players
      resources :tournament_registrations
      get '/lastest_tournaments' => "tournament_registrations#latest_tournaments"
    end
  end

  #WEB ROUTES
  resources :game_types
  resources :games
  resources :teams
  resources :tournaments do
    resources :tournament_registrations
  end
  devise_for :super_admins
  devise_scope :super_admin do
    authenticated :super_admin do
      root 'tournaments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
  before_action :set_game_type, only: %i[ show edit update destroy ]

  # GET /game_types or /game_types.json
  def index
    @game_types = GameType.all
  end

  # GET /game_types/1 or /game_types/1.json
  def show
  end

  # GET /game_types/new
  def new
    @game_type = GameType.new
  end

  # GET /game_types/1/edit
  def edit
  end

  # POST /game_types or /game_types.json
  def create
    @game_type = GameType.new(game_type_params)
    respond_to do |format|
      if @game_type.save
        format.html { redirect_to game_type_url(@game_type), notice: "Game type was successfully created." }
        format.json { render :show, status: :created, location: @game_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_types/1 or /game_types/1.json
  def update
    respond_to do |format|
      if @game_type.update(game_type_params)
        format.html { redirect_to game_type_url(@game_type), notice: "Game type was successfully updated." }
        format.json { render :show, status: :ok, location: @game_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_types/1 or /game_types/1.json
  def destroy
    @game_type.destroy

    respond_to do |format|
      format.html { redirect_to game_types_url, notice: "Game type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_type
      @game_type = GameType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_type_params
      params.require(:game_type).permit(:game_type)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/views/game_types/_form.html.erb
<%= form_with(model: game_type) do |form| %>
  <% if game_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_type.errors.count, "error") %> prohibited this game_type from being saved:</h2>

      <ul>
        <% game_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_type %>
    <%= form.text_field :game_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_types/edit.html.erb
<h1>Editing Game Type</h1>

<%= render 'form', game_type: @game_type %>

<%= link_to 'Show', @game_type %> |
<%= link_to 'Back', game_types_path %>

app/views/game_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Types</h1>

<table>
  <thead>
    <tr>
      <th>Game type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_types.each do |game_type| %>
      <tr>
        <td><%= game_type.game_type %></td>
        <td><%= link_to 'Show', game_type %></td>
        <td><%= link_to 'Edit', edit_game_type_path(game_type) %></td>
        <td><%= link_to 'Destroy', game_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Type', new_game_type_path %>

app/views/game_types/new.html.erb
<h1>New Game Type</h1>

<%= render 'form', game_type: @game_type %>

<%= link_to 'Back', game_types_path %>

app/views/game_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game type:</strong>
  <%= @game_type.game_type %>
</p>

<%= link_to 'Edit', edit_game_type_path(@game_type) %> |
<%= link_to 'Back', game_types_path %>