config/routes.rb
Rails.application.routes.draw do

  resources :platforms
  get 'teams/index'
  get 'teams/new'
  get 'teams/show'
  get 'teams/edit'
  #API ROUTES
  namespace :api do
    namespace :v1 do
      #ADMIN API ROUTES
      namespace :admin do
        resources :games, only: [:index, :create, :show, :update, :destroy] do
          collection do
            get :game_types
            get :get_all_games
          end
        end
        resources :tournaments, only: [:index, :create, :show, :update, :destroy]
      end

      post '/user/sign_in' => 'authentication#sign_in'
      post  '/user/sign_up' => "registrations#sign_up"
      post  '/user/sign_up_with_google' => "registrations#sign_up_with_google"
      resources :teams
      resources :players
      resources :tournament_registrations
      get '/lastest_tournaments' => "tournament_registrations#latest_tournaments"
    end
  end

  #WEB ROUTES
  resources :game_types
  resources :games
  resources :teams
  resources :tournaments do
    resources :tournament_registrations
  end
  devise_for :super_admins
  devise_scope :super_admin do
    authenticated :super_admin do
      root 'tournaments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_sidebar.html.erb
<div class=" d-flex flex-column flex-shrink-0 p-3" style="background-color: rgb(0, 65, 114); width: 280px; height: 100%;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-light text-decoration-none">
    <span class="fs-4 "> Gamers Machine</span>
    <img class="fs-4" src="<%= asset_path('gamelogo1.png')%>" style="width: 40px; height: 40px;">
  </a>
  <hr class="text-white border-2" >
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="/" class="nav-link link-light fs-3">
        <span><i class="fa fa-home"></i></span>
        <span>Home</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="/games" class="nav-link link-light fs-3">
        <span><i class="fa fa-gamepad"></i></span>
        <span>Games</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="/teams" class="nav-link link-light fs-3">
        <span><i class="fa fa-users"></i></span>
        <span>Teams</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="/tournaments" class="nav-link link-light fs-3">
        <span><i class="fa fa-trophy"></i></span>
        <span>Tournaments</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="<%= destroy_super_admin_session_path%>" data-method="delete", class="nav-link link-light fs-3">
        <span><i class="fa fa-power-off"></i></span>
        <span>Sign Out</span>
      </a>
    </li>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamersMachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>

  </head>

  <body>
    <section class="d-flex">
      <% if super_admin_signed_in? %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <main>
        <%= yield %>
      </main>
    </section>
  </body>
</html>